M48
; DRILL file {KiCad 8.0.7} date 2025-01-15T18:16:12+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-15T18:16:12+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X0.2522Y-0.185
X0.4797Y-0.185
T2
X0.0984Y-0.8858
X0.8858Y-0.1004
M30
