M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu24.04.1} date 2024-09-09T19:26:27+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-09-09T19:26:27+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X0.0984Y-0.8858
X0.8858Y-0.1004
M30
