M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-11-01T15:59:12+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-01T15:59:12+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X0.0984Y-0.8858
X0.8858Y-0.1004
M30
