M48
; DRILL file {KiCad 8.0.3-8.0.3-0~ubuntu24.04.1} date 2024-07-08T16:12:43+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-08T16:12:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.3-8.0.3-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X0.3665Y-0.1813
X0.5941Y-0.1813
T2
X0.0984Y-0.8858
X1.2008Y-0.1004
M30
